services:
  - name: halal-scanner-backend
    env:
      - name: PORT
        value: "3000"
      - key: MONGO_URI
        secret: MONGO_URI
      - name: NODE_ENV
        value: "production"
    ports:
      - port: 3000
        protocol: HTTP
    routes:
      - path: /
        port: 3000
    build:
      command: |
        npm install
        npm run build --if-present
      args:
        - --no-cache
      dockerfile: ./Dockerfile