services:
  - name: halal-scanner-backend
    env:
      - name: PORT
        value: "3000"
      - key: DATABASE_URL
        secret: DATABASE_URL
      - key: JWT_SECRET
        secret: JWT_SECRET
      - key: JWT_EXPIRES_IN
        secret: JWT_EXPIRES_IN
      - key: COHERE_API_KEY
        secret: COHERE_API_KEY
      - name: NODE_ENV
        value: "production"
    ports:
      - port: 3000
        protocol: HTTP
    routes:
      - path: /
        port: 3000
    build:
      command: |
        npm install
        npm run build --if-present
      args:
        - --no-cache
      dockerfile: ./Dockerfile